# Sign of Zs when input Z0 is negative

What should the convention be?

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import newton
from slab import SlabExact
plt.style.use('dark_background')
%matplotlib widget

In [2]:
A = SlabExact(scale=1e-5, Ts=[6.5, 1, 8, 2.5, 6.5],
      ns=[1, 1.44, 1, 1.44, 1], xrefs=[100, 40, 300, 40, 100],
      symmetric=True, wl=6.9e-6)

B = SlabExact(scale=1e-5, Ts=[6.5, 1, 8, 2.5, 6.5],
      ns=[2, 1.44, 2, 1.44, 2], xrefs=[100, 40, 300, 40, 100],
      symmetric=True, wl=6.9e-6)

In [9]:
Zs = np.array([[4+1j, 4-1j], [3, -1]])

In [11]:
A.Zi_from_Z0(Zs, A.ns)

array([[ 4.+1.j,  4.-1.j],
       [ 3.+0.j, -1.+0.j]])

In [68]:
def Zi_from_Z0(slab, Z0, ni):
    '''Get Z on region i (with refractive index ni) from Z0. Vectorized
    in Z0 and ni'''
    Z0, ni = np.array(Z0), np.array(ni)
    return (np.sign(Z0[..., np.newaxis]) * np.sqrt((ni[np.newaxis]**2 - slab.n0**2) * slab.K0**2 +
                   Z0[..., np.newaxis]**2, dtype=complex))
    return Zs

In [69]:
np.array([1,2,3,1])[np.newaxis]

array([[1, 2, 3, 1]])

In [74]:
Zi_from_Z0(A, Zs, [1,2])


array([[[  4.        +1.j        ,  16.24259654+0.24626604j],
        [  4.        -1.j        ,  16.24259654-0.24626604j]],

       [[  3.        +0.j        ,  16.05494614+0.j        ],
        [ -1.        +0.j        , -15.803838  +0.j        ]]])

In [30]:
Zi_from_Z0(B, Zs.real, np.array([1,2,2,1]))


array([[ 0.+15.25651649j,  4. +0.j        ,  4. +0.j        ,
         0.+15.25651649j],
       [-0.-15.25651649j, -4. +0.j        , -4. +0.j        ,
        -0.-15.25651649j]])

Question really though is what do we want?  If Z is real and positive, other region Zs should be positive (although possibly not real).  