# Vectorizing matrix multiplication

Issue I had that needed all the transposes was that I wanted to enter multiple indices at once like M[..., i, :] = np.array([a, b]).  That didn't work, and needed the transposes.  

In [1]:
import numpy as np

In [74]:
Zs1 = np.arange(6)
Zs2 = np.arange(6).reshape(2,3)

In [75]:
Zs1, Zs2

(array([0, 1, 2, 3, 4, 5]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [142]:
def M(Z):
    out = np.zeros(Z.shape + (2,2))
    # out[..., 0, 0] = Z
    # out[..., 0, 1] = 2 * Z**2
    # out[..., 1, 0] = np.zeros_like(Z)
    # out[..., 1, 1] = np.sin(Z)
    out[..., 0] = np.array([Z, (2 * Z**2)])
    # out[..., 1, :] = np.zeros_like(Z), np.sin(Z)
    return out

def N(Z):
    out = np.zeros(Z.shape + (2,2))
    out[..., 0, 0] = -2 * np.ones_like(Z)
    out[..., 0, 1] = 3 * Z
    out[..., 1, 0] = Z
    out[..., 1, 1] = -5 * Z
    return out

In [143]:
np.array([Zs2, Zs2]).shape

(2, 2, 3)

In [144]:
(N(Zs2) @ M(Zs2))[1,1], N(Zs2)[1,1] @ M(Zs2)[1,1]

ValueError: could not broadcast input array from shape (2,2,3) into shape (2,3,2)

Let's see about automating the check:  say Zs are 2x2, we should have (M(Zs) @ N(Zs))[i, j] = M(Zs[i, j] ) @ N(Zs[i, j] )

or more generally if [idx] is a integer list that yields a single number from Zs we should have (M(Zs) @ N(Zs))[[idx]] = M(Zs[idx] ) @ N(Zs[idx] ).

In [105]:
def check2d(Zs):
    MZs, NZs = M(Zs), N(Zs)
    prod = MZs @ NZs
    s = 0
    for i in range(Zs.shape[0]):
        for j in range(Zs.shape[1]):
            lhs = prod[i, j] 
            rhs = MZs[i, j] @ NZs[i, j]
            s += lhs - rhs
    return s

In [106]:
check2d(Zs2)

array([[0., 0.],
       [0., 0.]])