# Eigenvectors of Q matrix

Here we see what they look like and if this gives any insight into why the spectral integral associated with mode classes built from the eigenvectors is so nice.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from slab import SlabExact
plt.style.use('dark_background')
%matplotlib widget

In [2]:
A = SlabExact(scale=1e-5, Ts=[6.5, 1, 8, 1, 6.5],
              ns=[1, 1.44, 1, 1.44, 1], xrefs=[100, 40, 300, 40, 100],
              symmetric=True, no_xs=True, wl=5e-5)

In [3]:
C = 1 + .1j

In [4]:
M = A.transmission_matrix(C, Ztype_far_left='standard', Ztype_far_right='standard')[0]
B = np.array([[0, 1], [1,0]])
Q = B + M.T @ B @ M

trQs = M[..., 0, 0] * M[..., 1, 0] + \
    M[..., 0, 1] * M[..., 1, 1]

Lp = trQs + np.sqrt(trQs**2 + 4 *  M[..., 0, 0] * M[..., 1, 1], dtype=complex)
Lm = trQs - np.sqrt(trQs**2 + 4 *  M[..., 0, 0] * M[..., 1, 1], dtype=complex)

C1p = 2 * M[..., 0, 0] * M[..., 1, 1]
C1m = 2 * M[..., 0, 0] * M[..., 1, 1]
C2p = Lp - 2 * M[..., 0, 0] * M[..., 1, 0]
C2m = Lm - 2 * M[..., 0, 0] * M[..., 1, 0]

factorp = np.sqrt(Lp * (C1p ** 2 + C2p ** 2), dtype=complex)
factorm = np.sqrt(Lm * (C1m ** 2 + C2m ** 2), dtype=complex)

vp = np.sqrt(2 / np.pi) * np.array([C1p, C2p]) / factorp
vm = np.sqrt(2 / np.pi) * np.array([C1m, C2m]) / factorm

In [5]:
Eig = A.normalizer('eigvec')

In [6]:
Eig.normalization(C, sign=1)[0].T[0], Eig.normalization(C, sign=-1)[0].T[0]

(array([0.45652371+0.09059983j, 0.62343014-0.16802418j]),
 array([ 0.03598966-0.19159055j, -0.08446459+0.11230269j]))

In [7]:
vp, vm

(array([0.45652371+0.09059983j, 0.62343014-0.16802418j]),
 array([ 0.03598966-0.19159055j, -0.08446459+0.11230269j]))

In [8]:
(Q @ vp) - (Lp * vp)

array([5.55111512e-17+4.16333634e-16j, 3.33066907e-16+2.77555756e-17j])

In [9]:
(Q @ vm) - (Lm * vm)

array([ 2.22044605e-16+0.00000000e+00j, -1.66533454e-16+2.22044605e-16j])

In [10]:
vp.T @ vm

(-6.938893903907228e-18+6.938893903907228e-18j)

In [11]:
vp.T @ vp

(0.5606385889007923-0.12678073145912666j)