# Vectorize application of matrix to vector

So that we can apply the transfer matrix iteratively to an array of vectors.  I have done this before, but kind of didn't like how I did it.  However, it looks like I did it right, there's no better way I find below.

In [1]:
import numpy as np

In [36]:
Cs = np.array([[1,2,3], [1,2,3]])

M = np.zeros(Cs.shape + (2,2))
M[..., 0,0] = Cs
M[..., 0,1] = np.sin(Cs)
M[..., 1,0] = Cs / 2

In [37]:
M[0]

array([[[1.        , 0.84147098],
        [0.5       , 0.        ]],

       [[2.        , 0.90929743],
        [1.        , 0.        ]],

       [[3.        , 0.14112001],
        [1.5       , 0.        ]]])

In [38]:
V = np.zeros(Cs.shape + (2, 1))
V[..., 0, 0] = Cs
V[..., 1, 0] = -Cs

In [39]:
M[0] @ np.ones((2, 1))

array([[[1.84147098],
        [0.5       ]],

       [[2.90929743],
        [1.        ]],

       [[3.14112001],
        [1.5       ]]])

In [43]:
(M @ V)[0,0]

array([[0.15852902],
       [0.5       ]])

In [42]:
M[0,0] @ V[0,0]

array([[0.15852902],
       [0.5       ]])

One thing that might be useful though is doing the row vector version

In [52]:
Vr = np.zeros(Cs.shape + (1, 2))
Vr[..., 0, 0] = 2*Cs
Vr[..., 0, 1] = -.5*Cs
Vr

array([[[[ 2. , -0.5]],

        [[ 4. , -1. ]],

        [[ 6. , -1.5]]],


       [[[ 2. , -0.5]],

        [[ 4. , -1. ]],

        [[ 6. , -1.5]]]])

In [55]:
Vr @ M

array([[[[ 1.75      ,  1.68294197]],

        [[ 7.        ,  3.63718971]],

        [[15.75      ,  0.84672005]]],


       [[[ 1.75      ,  1.68294197]],

        [[ 7.        ,  3.63718971]],

        [[15.75      ,  0.84672005]]]])

In [61]:
M.transpose(np.arange(len(M.shape))).shape

(2, 3, 2, 2)

In [63]:
t_idx = np.arange(len(M.shape))
t_idx[-2], t_idx[-1] = t_idx[-1], t_idx[-2]

In [64]:
t_idx

array([0, 1, 3, 2])