# Properties of transfer matrix entries

Investigations for symmetric structures in Z plane

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from slab import SlabExact, plotlogf, plotlogf_real
from scipy.optimize import newton
from IPython.display import Video


In [14]:
A = SlabExact()

In [59]:
Z0 = 10 - 20j
rho = A.rhos[0]
nl, nr = A.ns[1], A.ns[2]
T = A.transfer_matrix_Z(Z0, rho, nl, nr)


In [60]:
T 

array([[0.99795644+0.00274051j, 0.00204383-0.00274064j],
       [0.00204356-0.00274051j, 0.99795617+0.00274064j]])

In [61]:
Z_left = A.Zi_from_Z0(Z0, nl)
Z_right = A.Zi_from_Z0(Z0, nr)

In [62]:
Z_left, Z_right

((10.068749054921339-19.86344072228568j), (10-20j))

In [63]:
T * 2 * Z_right

array([[20.06874905-39.86344755j, -0.06874905 -0.1365661j ],
       [-0.06874905 -0.13655245j, 20.06874905-39.8634339j ]])

In [64]:
np.exp(1j * rho * (Z_left - Z_right)), np.exp(-1j * rho * (Z_left - Z_right))

((1.0000001365592845-6.874906430966084e-08j),
 (0.9999998634407293+6.874904553301829e-08j))

## Possible truths

- Seems likely that $$M(\bar{Z}) \bar{M}(Z) = I$$ holds for any $Z\in \mathbb{C}.$

- Also seems likely that entries $b$ and $c$ are equal and opposite for any $Z \in \mathbb{C}.$  They aren't pure imaginary anymore however.

## More complex guide

In [41]:
B = SlabExact(ns=[1.3, 1.4, 1.5, 1.4, 1.3], Ts=[1,1,1,1,1], symmetric=True, xrefs=5*[10])

In [42]:
Z = 10 + 5j
MZ = B.transmission_matrix_Z(Z)
MZconj = B.transmission_matrix_Z(Z.conjugate())

In [43]:
MZ

array([[-3.13442683e+08-1.56524649e+08j, -1.64073604e+04+5.89992583e+02j],
       [ 1.64073604e+04-5.89992583e+02j,  6.61850920e-01-3.92277221e-01j]])

In [44]:
MZconj.conjugate()

array([[ 6.61850920e-01-3.92277221e-01j,  1.64073604e+04-5.89992583e+02j],
       [-1.64073604e+04+5.89992583e+02j, -3.13442683e+08-1.56524649e+08j]])

In [45]:
MZ @ MZconj.conjugate()

array([[ 1.00000000e+00+0.00000000e+00j, -8.33301310e-04+9.76562500e-04j],
       [ 2.39022982e-13-9.09494702e-13j,  9.99999993e-01-5.96046448e-08j]])

## Non-symmetric guide

In [46]:
C = SlabExact(ns=[1.3, 1.4, 1.5, 1.3], Ts=[1,1,1,1], symmetric=True, xrefs=4*[10])

In [47]:
Z = 10 + 5j
MZ = C.transmission_matrix_Z(Z)
MZconj = C.transmission_matrix_Z(Z.conjugate())

In [48]:
MZ

array([[ 6.41998915e+03-3.43032274e+04j,  1.88506937e+02+1.52895570e+02j],
       [-9.24703013e+01-7.33575486e+01j,  7.54932244e-01-3.22445051e-01j]])

In [101]:
MZconj.conjugate()

array([[ 7.54932244e-01-3.22445051e-01j, -9.24703013e+01-7.33575486e+01j],
       [ 1.88506937e+02+1.52895570e+02j,  6.41998915e+03-3.43032274e+04j]])

In [102]:
MZ @ MZconj.conjugate()

array([[ 5.94356105e+03+2.96770448e+04j,  3.34496498e+06-2.78373332e+06j],
       [ 9.81477942e+01+2.90792787e+01j, -3.04482241e+03-1.43999169e+04j]])

## Guide with different outer indices of refraction

In [103]:
D = SlabExact(ns=[1.3, 1.4, 1.2], Ts=[1,1,1], symmetric=True, xrefs=3*[10])

In [104]:
Z = 10 + 5j
MZ = D.transmission_matrix_Z(Z)
MZconj = D.transmission_matrix_Z(Z.conjugate())

In [105]:
MZ

array([[ 2.84692554+0.33301498j, -0.01200436-1.8232415j ],
       [ 0.10477512+0.87729552j,  0.89427337-0.17890571j]])

In [106]:
MZconj.conjugate()

array([[ 0.89427337-0.17890571j,  0.10477512+0.87729552j],
       [-0.01200436-1.8232415j ,  2.84692554+0.33301498j]])

In [107]:
MZ @ MZconj.conjugate()

array([[-0.71855747-0.16775113j,  0.57912566-2.66214372j],
       [-0.08627271-0.86253152j,  1.84683838-0.02768732j]])